### ISSUE TITLE
BlackboardCondition with Operator.ON_CHANGE

### ISSUE THREAD

**Issue by MohHeader** [meniku/NPBehave#2]
If I have something like this :
```
new BlackboardCondition ("SomeThing,,, Looking forward to be changed", Operator.ON_CHANGE, Stops.LOWER_PRIORITY,
	new Action(() => Debug.Log("Well,,, that something has been changed"))
)
```

Would fire with every loop( even though the key hasn't changed ) 
```
private bool IsConditionMet()
{
       if (op == Operator.ON_CHANGE)
       {
              return true;
       }
...
}
```
The expected behavior : Not to Fire unless the key really changed.

I thought that something like that would fix the issue :
```
        protected override void DoStart()
        {
            if (stopsOnChange != Stops.NONE)
            {
                this.RootNode.Blackboard.AddObserver(this.key, OnValueChanged);
            }

            if (this.op == Operator.ON_CHANGE || !IsConditionMet())
            {
                Stopped(false);
            }
            else
            {
                Decoratee.Start();
            }
        }
```
But now it don't fire at all.

I am feeling that may be I am the one who don't get it's intended use.

Thanks,

**Comment by meniku** [comment]
Yes you're right. The idea behind the ON_CHANGE is not really clear from it's name.

The idea was to have no condition on the value itself (that's why it's always true), but rather have the possibility to re-evaluate the "stops condition" whenever the value in the blackboard changed. I think this was useful to me to be sure a specific subranch is always re-executed on a value change, regardless of it's contents. For a loop by that would also execute like you pointed out.

The thing you want to achieve would require the decorator to remember the last known value of the blackboard and then compare this on execution. I can add such a decorator this evening (or at least post you some code here) if you like.

I will defiantly rename the Operator.ON_CHANGE operator to something like Operator.ALWAYS_TRUE, as it's indeed confusing right now.

**Comment by meniku** [comment]
You could create your own new node type that does track for changes on a blackboard key. Something like that should work for you:

```
using NPBehave;

public class BlackboardValueChanged : Decorator
{
    private object lastValue;
    private string blackboardKey;

    public BlackboardValueChanged(string blackboardKey, Node decoratee) : base("BlackboardValueChanged", decoratee)
    {
        this.lastValue = null;
        this.blackboardKey = blackboardKey;
    }

    protected override void DoStart()
    {
        object newValue = RootNode.Blackboard.Get(blackboardKey);
        if (lastValue != newValue)
        {
            lastValue = newValue;
            Decoratee.Start();
        }
        else
        {
            Stopped(false);
        }
    }

    override protected void DoStop()
    {
        Decoratee.Stop();
    }

    protected override void DoChildStopped(Node child, bool result)
    {
        Stopped(result);
    }
}
```

I didn't test it, but I think you should be able to adjust it for your needs.

**Comment by MohHeader** [comment]
Aha Ok, 

I got it now, only naming thing,, 
No worries,

And thanks for the "BlackboardValueChanged" code.
👍
